version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: post
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  openbao:
    image: openbao/openbao:latest
    container_name: openbao
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
      OPENBAO_TOKEN: root
    # НЕ монтируем volume, чтобы каждый раз генерился новый контейнер с токеном root
    depends_on:
      - postgres

volumes:
  pgdata:
